# Generated by Django 3.2.7 on 2022-06-24 09:37

import blog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('message', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('post_image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='Image')),
                ('description', models.TextField()),
                ('inline_image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='Image')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField(null=True)),
                ('post_image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='Image')),
                ('inline_image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=blog.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('post_image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='Image')),
                ('description', models.TextField()),
                ('inline_image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=blog.models.upload_to, verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=blog.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.projectcategory')),
            ],
        ),
    ]
